import {test} from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {createAI} from '../src/ai.mjs';
test('摘要真正流式：结束前回调、跨字节 UTF-8、DeepSeek 关闭思考',async()=>{
 const home=await fs.mkdtemp(path.join(os.tmpdir(),'skills-stream-'));let request,ended=false,first=false;
 const upstream=http.createServer(async(req,res)=>{let raw='';for await(const c of req)raw+=c;request=JSON.parse(raw);res.writeHead(200,{'Content-Type':'text/event-stream'});const part=Buffer.from('data: '+JSON.stringify({choices:[{delta:{content:'你好'}}]})+'\r\n\r\n');const cut=part.indexOf(Buffer.from('你'))+1;res.write(part.subarray(0,cut));setTimeout(()=>res.write(part.subarray(cut)),10);setTimeout(()=>{ended=true;res.end('data: '+JSON.stringify({choices:[{delta:{content:'，世界'},finish_reason:'stop'}]})+'\n\ndata: [DONE]\n\n');},80);});await new Promise(r=>upstream.listen(0,'127.0.0.1',r));
 try{const ai=createAI(home,{platform:'linux',env:{OPENAI_API_KEY:'test',OPENAI_MODEL:'deepseek-v4-flash',OPENAI_BASE_URL:'http://127.0.0.1:'+upstream.address().port}});const r=await ai.generate({mode:'summary',content:'fixture',onDelta:()=>{if(!ended)first=true;}});assert.equal(request.stream,true);assert.deepEqual(request.thinking,{type:'disabled'});assert.equal(first,true);assert.equal(r.text,'你好，世界');}finally{await new Promise(r=>upstream.close(r));await fs.rm(home,{recursive:true,force:true});}
});

test('流式失败不伪装成完成，普通 JSON 响应兼容且不重发',async()=>{
 const home=await fs.mkdtemp(path.join(os.tmpdir(),'skills-stream-error-'));let variant='json',calls=0;
 const upstream=http.createServer(async(req,res)=>{for await(const c of req){}calls++;if(variant==='json'){res.setHeader('Content-Type','application/json');res.end(JSON.stringify({choices:[{message:{content:'兼容结果'},finish_reason:'stop'}]}));}else{res.setHeader('Content-Type','text/event-stream');res.end('data: '+JSON.stringify({choices:[{delta:{content:'部分内容'}}]})+'\n\n');}});await new Promise(r=>upstream.listen(0,'127.0.0.1',r));
 try{const ai=createAI(home,{platform:'linux',env:{OPENAI_API_KEY:'test',OPENAI_BASE_URL:'http://127.0.0.1:'+upstream.address().port}});let text='';await ai.generate({mode:'summary',content:'fixture',onDelta:d=>text+=d});assert.equal(text,'兼容结果');assert.equal(calls,1);variant='broken';await assert.rejects(ai.generate({mode:'summary',content:'fixture',onDelta:()=>{}}),/提前结束/);}finally{await new Promise(r=>upstream.close(r));await fs.rm(home,{recursive:true,force:true});}
});
